services:
  web: 
    build: ./docker
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html/coc
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
      - MYSQL_USER=db
      - MYSQL_PASSWORD=tiger
    volumes:
      - ./storage:/var/lib/mysql
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8001:80"

